version: '2'
services:
    exerciseapplication-app:
        image: exerciseapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://exerciseapplication-mysql:3306/exerciseapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    exerciseapplication-mysql:
        extends:
            file: mysql.yml
            service: exerciseapplication-mysql
