# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjIxODMxZGJiNWU2MGUyMzFjMzhmOTdkZTFhZDlkNDE1YmU2ZmRlZTVlMTIxNmQ5MjU3YTQ4NTNlNGZjMjU3ZGNiMGI5NTM5Mzg1N2IwZWVjNDAxYzJhNjlhZWRjMDg2MTQ3OGQzZWNlNDYwMzI2YTFhOWM0MTFhZGYyMGE1MmU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
