name: Run Cypress E2E Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_DATABASE: Artemis
          MYSQL_ROOT_PASSWORD: rootPassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

  execute-tests:
    runs-on: ubuntu-latest
    environment:
        name: artemistest5-e2e-tests
        url: https://artemistest5.ase.in.tum.de
    concurrency: cypress-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: src/test/cypress
          browser: chrome
          install-command: yarn install --frozen-lockfile
          config: baseUrl=https://artemistest5.ase.in.tum.de
          env: username=${{ secrets.BAMBOO_TEST_USER }},password=${{ secrets.BAMBOO_TEST_PASSWORD }},adminUsername=${{ secrets.BAMBOO_ADMIN_USER }},adminPassword=${{ secrets.BAMBOO_ADMIN_PASSWORD }}
