name: Run Cypress E2E Tests
on: push

env:
  CI: true
  node: 14.x
  java: 16

jobs:
  execute-tests:
    runs-on: ubuntu-latest
#    environment:
#        name: artemistest5-e2e-tests
#        url: https://artemistest5.ase.in.tum.de
#    concurrency: cypress-tests
    
    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_DATABASE: Artemis
          MYSQL_ROOT_PASSWORD: rootPassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '${{ env.node }}'
          cache: 'npm'
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '${{ env.java }}'
          cache: 'gradle'
      - name: Production Build
        run: ./gradlew -Pprod -Pwar clean bootWar
        env:
          NODE_OPTIONS: --max_old_space_size=6144
      
      - name: Start Artemis
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/Artemis?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
          SPRING_PROFILES_ACTIVE: dev,bamboo,bitbucket,jira,artemis,scheduling
        run: java -jar build/libs/*.war

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: src/test/cypress
          browser: chrome
          install-command: yarn install --frozen-lockfile
          config: baseUrl=http://localhost:8080
          env: username=${{ secrets.BAMBOO_TEST_USER }},password=${{ secrets.BAMBOO_TEST_PASSWORD }},adminUsername=${{ secrets.BAMBOO_ADMIN_USER }},adminPassword=${{ secrets.BAMBOO_ADMIN_PASSWORD }}
