name: Pull Request Ready for Review
on:
  pull_request:
    types: [labeled]

jobs:
  addToProject:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
